# https://api.github.com/repos/german-muzquiz/spinnaker-scratchpad/contents/kubernetes-manifests/nginx-dep.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: index.docker.io/library/nginx
          name: nginx
          ports:
            - containerPort: 80
          env:
            a: ${lol}
